### ISSUE TITLE
Common-sense QA checklist

### ISSUE THREAD

**Issue by neubig** [neulab/gemini-benchmark#10]
* [x] Output generation code that supports litellm checked into the repo
* [ ] System outputs for OpenAI models checked in to the repo
* [x] Zeno visualization code checked into the repo
* [ ] Zeno project shared on the slack and with the "Benchmarking Gemini" Zeno group.
* [ ] Confirmation that the results using OpenAI models are reasonable and more-or-less match previous work
* [ ] System outputs for Gemini (through Vertex AI) checked in to the repo and uploaded to the Zeno project
* [ ] Overall numerical results added to the paper
* [ ] Analysis is done of the results and text and examples are added to the paper
* [ ] (Optional) Also created results for Mixtral (through Together)
