### ISSUE TITLE
Mathematical Reasoning Checklist

### ISSUE THREAD

**Issue by neubig** [neulab/gemini-benchmark#11]
* [x] Output generation code that supports litellm checked into the repo
* [x] System outputs for OpenAI models checked in to the repo
* [x] Zeno visualization code checked into the repo
* [x] Zeno project shared on the slack and with the "Benchmarking Gemini" Zeno group.
* [x] Confirmation that the results using OpenAI models are reasonable and more-or-less match previous work
* [x] System outputs for Gemini (through Vertex AI) checked in to the repo and uploaded to the Zeno project
* [x] Overall numerical results added to the paper
* [x] Analysis is done of the results and text and examples are added to the paper
* [x] (Optional) Also created results for Mixtral (through Together)
